### ISSUE TITLE
Schema pattern matching always comes back valid

### ISSUE THREAD

**Issue by mehagar** [netmail-open/wjelement#45] opened 2015-07-27 15:01 UTC
Schema:

```JavaScript
{
    "$schema": "http://json-schema.org/draft-03/schema#",
    "type": "object",
    "properties": {
      "key": {
        "type": "string",
        "pattern": "ABC"
      }
    }
}
```

JSON String to validate

```JavaScript
{
  "key": "123"
}
```

Example

```C++
   std::string jsonString = "{\n  \"key\": \"123\"\n}";
   WJReader reader = WJROpenMemDocument((void*)jsonString.c_str(), NULL, 0);
   WJElement doc = WJEOpenDocument(reader, NULL, NULL, NULL);

   std::string schemaString = "{\n    \"$schema\": \"http://json-schema.org/draft-03/schema#\",\n    \"type\": \"object\",\n    \"properties\": {\n      \"key\": {\n        \"type\": \"string\",\n        \"pattern\": \"ABC\"\n      }\n    }\n}";
   WJReader SchemaReader = WJROpenMemDocument((void*)schemaString.c_str(), NULL, 0);
   WJElement SchemaDoc = WJEOpenDocument(SchemaReader, NULL, NULL, NULL);

   if(WJESchemaValidate(
      SchemaDoc, doc,
      NULL, NULL, NULL, NULL))
   {
      std::cout << "schema matches\n";
   }
   else
   {
      std::cout << "schema does not match\n";
   }

```

This prints "schema matches\n", as does any other setting of the pattern.

**Comment by penduin** [comment] 2015-07-27 16:09
The regex library isn't a hard dependency for WJElement, but I should
mention in the docs that parts of schema validation won't work as
expected without it.

Your code builds and runs as intended, actually.  :^)  I'm guessing
that when you configured with cmake, you got this message:
***  WARNING: GNU C regex library not found.
     WJESchemaValidate() will not support patternProperties

I should tweak that to also mention "pattern", which uses the same
regex library.  If you're building on a non-GNU C library, I think
there are several other regular expression libs which use the same
interface (and provide a compatible regex.h) but I don't know where to
point you off the top of my head.

Is that enough for you to go on?

**Comment by mehagar** [comment] 2015-07-27 19:07
I am indeed using a Windows library. I'll try using a compatible regex one for windows.

**Comment by minego** [comment] 2015-07-27 19:09
Please let us know if you find one that works so we can update instructions
for building on windows.

**Comment by mehagar** [comment] 2015-07-27 21:27
I will. For now, it is appropriate to close this issue? The initial question has been answered.

**Comment by minego** [comment] 2015-07-27 21:28
Perhaps the ticket should stay open until we have updated the build to 
make it clearer that this will happen? What do you think Owen?

**Comment by penduin** [comment] 2015-07-27 22:22
Yeah let's see what we learn here; there might be something we should
at least document before closing this.  Thanks!

**Comment by penduin** [comment] 2015-08-28 18:46
Haven't heard anything in a while, so I've just made the build warning more explicit if the regex library is absent.

I'll be happy to add further documentation and/or alternate library support if anyone has any such suggestions!

**Closed by penduin** 2015-08-28 18:46 UTC
